#ifndef PARADOX_WORKS_CPP_3D_RENDERER_DEFINES_HPP
#define PARADOX_WORKS_CPP_3D_RENDERER_DEFINES_HPP

#include <paradox-platform/defines.hpp>

#ifdef PARADOX_3D_RENDERER_STATIC
    #define PARADOX_3D_RENDERER_API
#elif PARADOX_3D_RENDERER_BUILD_DLL
    #define PARADOX_3D_RENDERER_API PARADOX_EXPORT
#else
    #define PARADOX_3D_RENDERER_API PARADOX_IMPORT
#endif

#endif