#ifndef PARADOX_WORKS_C_3D_RENDERER_DEFINES_H
#define PARADOX_WORKS_C_3D_RENDERER_DEFINES_H

#include <paradox-platform/defines.h>

#ifdef PARADOX_3D_RENDERER_STATIC
    #define PARADOX_3D_RENDERER_API
#elif PARADOX_3D_RENDERER_BUILD_DLL
    #define PARADOX_3D_RENDERER_API PARADOX_EXPORT
#else
    #define PARADOX_3D_RENDERER_API PARADOX_IMPORT
#endif

#endif