#ifndef PARADOX_SOFTWARE_C_HEADER_3D_RENDERER_DEFINES
#define PARADOX_SOFTWARE_C_HEADER_3D_RENDERER_DEFINES

#include <paradox-application/defines.h>

#ifdef PARADOX_3D_RENDERER_STATIC
    #define PARADOX_3D_RENDERER_API
#elif PARADOX_3D_RENDERER_BUILD_DLL
    #define PARADOX_3D_RENDERER_API PARADOX_EXPORT
#else
    #define PARADOX_3D_RENDERER_API PARADOX_IMPORT
#endif

#endif